# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package-lock.json, package.json]

locale: uk

ampscript:
  gastring: "?%%=v(@gaString)=%%"
  emailaddr: "%%emailaddr%%"
  view-online: "%%view_email_url%%"

partner:
  name: Jersey
  link: "https://www.jersey.com/"
  logo-width: 140
  logo-min-width: 110 # mobile & fallback
