# Site settings
title: Jersey
locale: uk
partner:
  name: Jersey
  link: "https://www.jersey.com/"

description: >
  Autumn is calling - reconnect and rebalance with an effortless escape to Jersey. Around an hour away by air or a short ferry crossing, Jersey is wonderfully easy to get to, whilst still feeling like a bit of an adventure. Once there, discover a dramatic coastline, mile upon mile of peaceful country lanes, and a history brimming with fascinating stories. Throw yourself into the great outdoors and build up an appetite for award-winning local food, as fresh as the sea air that rolls in from the coast. Discover it this autumn, for a revitalising escape.



# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2021/jersey" # the subpath of your site, e.g. /blog/
img:     "/uk/2021/jersey/_assets/img"
css:     "/uk/2021/jersey/_assets/css"
js:      "/uk/2021/jersey/_assets/js"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
